### ISSUE TITLE
typecho 1.2RC2 报错 500

### ISSUE THREAD

**Issue by Sagit-chu** [soxft/CommentToMail#2]
![image](https://user-images.githubusercontent.com/36596628/160263985-baefe34f-4b70-44fc-a0e3-85591997388b.png)

**Comment by soxft** [comment]
> ![image](https://user-images.githubusercontent.com/36596628/160263985-baefe34f-4b70-44fc-a0e3-85591997388b.png)
> 
> 

尝试在config.ini.php中 添加

define('__TYPECHO_DEBUG__', true);
打开typecho的debug模式，看一下详细报错

**Comment by Sagit-chu** [comment]
```
syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)
ParseError: syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /var/www/html/usr/plugins/CommentToMail/Console.php:31
Stack trace:
#0 [internal function]: Typecho\{closure}('TypechoPlugin\\C...')
#1 /var/www/html/var/Typecho/Widget.php(154): spl_autoload_call('TypechoPlugin\\C...')
#2 /var/www/html/usr/plugins/CommentToMail/page/console.php(49): Typecho\Widget::widget('TypechoPlugin\\C...')
#3 /var/www/html/sagit457x/extending.php(14): require_once('/var/www/html/u...')
#4 {main}
```

**Comment by soxft** [comment]
使用的是什么php版本呢

**Comment by Sagit-chu** [comment]
7.3.29-fpm

**Comment by Sagit-chu** [comment]
要使用8.0+吗

**Comment by soxft** [comment]
> 要使用8.0+吗
> 
> 

是的

**Comment by Sagit-chu** [comment]
好吧，我试试

**Comment by Sagit-chu** [comment]
php 8.0 fpm
访问action地址的时候报错
```
Cannot assign stdClass to property TypechoPlugin\CommentToMail\Action::$_comment of type TypechoPlugin\CommentToMail\lib\Comment
TypeError: Cannot assign stdClass to property TypechoPlugin\CommentToMail\Action::$_comment of type TypechoPlugin\CommentToMail\lib\Comment in /var/www/html/usr/plugins/CommentToMail/Action.php:142
Stack trace:
#0 /var/www/html/usr/plugins/CommentToMail/Action.php(99): TypechoPlugin\CommentToMail\Action->deliverMail('gTSTrM6PzptWg49...')
#1 /var/www/html/var/Widget/Action.php(71): TypechoPlugin\CommentToMail\Action->action()
#2 /var/www/html/var/Typecho/Widget.php(155): Widget\Action->execute()
#3 /var/www/html/var/Typecho/Router.php(96): Typecho\Widget::widget('Widget_Do', NULL, Array)
#4 /var/www/html/index.php(23): Typecho\Router::dispatch()
#5 {main}
```

**Comment by soxft** [comment]
这个 貌似是, 对 数据库内邮件数据unserialize时 数据类型不一样的问题

可能是, 之前使用过类似的插件?

**Comment by Sagit-chu** [comment]
是的，要删掉数据库哪个条目吗

**Comment by soxft** [comment]
试试 删掉原来的那张表, 重新安装一遍插件

**Comment by Sagit-chu** [comment]
好的

**Comment by Sagit-chu** [comment]
是这张吗
![image](https://user-images.githubusercontent.com/36596628/160267083-136104c2-84c4-4fb4-95b5-0b66792cc5d4.png)

**Comment by soxft** [comment]
对的

**Comment by Sagit-chu** [comment]
可以了

**Comment by Sagit-chu** [comment]
action 又有这样的错误了
```
<pre><code><h1>TypechoPlugin\CommentToMail\Action::deliverMail(): Argument #1 ($key) must be of type string, null given, called in /var/www/html/usr/plugins/CommentToMail/Action.php on line 99</h1>TypeError: TypechoPlugin\CommentToMail\Action::deliverMail(): Argument #1 ($key) must be of type string, null given, called in /var/www/html/usr/plugins/CommentToMail/Action.php on line 99 and defined in /var/www/html/usr/plugins/CommentToMail/Action.php:127
Stack trace:
#0 /var/www/html/usr/plugins/CommentToMail/Action.php(99): TypechoPlugin\CommentToMail\Action-&gt;deliverMail(NULL)
#1 /var/www/html/var/Widget/Action.php(71): TypechoPlugin\CommentToMail\Action-&gt;action()
#2 /var/www/html/var/Typecho/Widget.php(155): Widget\Action-&gt;execute()
#3 /var/www/html/var/Typecho/Router.php(96): Typecho\Widget::widget('Widget_Do', NULL, Array)
#4 /var/www/html/index.php(23): Typecho\Router::dispatch()
#5 {main}</code></pre>

```

**Comment by Sagit-chu** [comment]
用浏览器访问会导致网站504，只能用curl

**Comment by soxft** [comment]
> 用浏览器访问会导致网站504，只能用curl

可以用 uptimerobot 等工具 定时访问

**Comment by soxft** [comment]
访问 action 时要指定 后台设置的秘钥. 
我忘记做空安全处理了. 后面会加一下

**Comment by Sagit-chu** [comment]
我是加上密钥访问的😂 但是也报错

**Comment by soxft** [comment]
啊😂 网址 应该类似 https://blog.xsot.cn/action/comment-to-mail?do=deliverMail&key=xxxxxxxx
这样 你看一下

**Comment by Sagit-chu** [comment]
是这样的

**Comment by soxft** [comment]
啊 那这个 就不太清楚了, 我等会儿换成RC2看下 . 我可能用的是rc1

**Comment by Sagit-chu** [comment]
😂😂好吧

**Comment by Sagit-chu** [comment]
刚装插件第一次访问还好好的，然后我测试发件，给博客卡成504了，然后我用curl试了一下发现这个报错

**Comment by soxft** [comment]
<img width="880" alt="image" src="https://user-images.githubusercontent.com/42080379/160272604-3f16350d-e20f-4353-832e-9b3f3bb198c2.png">

升级到 RC2 貌似 我是可以正常使用的, 可能是其他插件冲突吗？

**Comment by Sagit-chu** [comment]
![Screenshot_2022-03-27-16-04-53-222_com android chrome](https://user-images.githubusercontent.com/36596628/160272659-53a3888a-9152-4f0d-b047-50c4518d68c9.jpg)
这。。。可能是哪个

**Comment by soxft** [comment]
要不 加个 QQ 群? NjA4MjY1OTEy看下

**Comment by Sagit-chu** [comment]
群号多少

**Comment by soxft** [comment]
608265912  直接加吧
